version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytest
      - export PYTHONPATH=$PYTHONPATH:$CODEBUILD_SRC_DIR/src
  build:
    commands:
      - pytest tests/test.py  # Führt die Tests aus
